version: "3.8"

services:
  db:
    image: mysql:8.1.0
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network
    profiles:
      - prod

  app-dev:
    build:
      context: ./app
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - db
    networks:
      - app-network
    profiles:
      - dev

  app-prod:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    env_file:
      - ./app/.env
    depends_on:
      - db
    networks:
      - app-network
    profiles:
      - prod

networks:
  app-network:
    driver: bridge

volumes:
  db_data: